version: '3.9'
services:
  client:
    image: ${AWS_CLIENT_IMAGE}
    hostname: client
    ports:
      - "3000:3000"
    build: .
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    entrypoint: [npm, run, start]
    labels:
      - "com.moviefav.description=Client"
      - "com.moviefav.client"
      - "kompose.service.type=nodeport"
    restart: "on-failure"
    networks:
      - client


###################################################
# List of all networks needed
#
networks:
  client:

