version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/microservices"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "africanpilot"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/microservices"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "africanpilot"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Theater app dependencies
  - package-ecosystem: "npm"
    directory: "/microservices/apps/theater"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "africanpilot"
    commit-message:
      prefix: "deps(theater)"
      prefix-development: "deps-dev(theater)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/microservices"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    assignees:
      - "africanpilot"
    commit-message:
      prefix: "deps(docker)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    assignees:
      - "africanpilot"
    commit-message:
      prefix: "deps(actions)"
