version: '3.9'
services:
  nginxfortress:
    image: ${AWS_NGINX_APOLLO_IMAGE}
    hostname: nginxfortress
    build: .
    restart: always
    volumes:
      - ./templates:/etc/nginxfortress/templates
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    networks:
      - fortress
      - api
      - client
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    networks:
      - fortress
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  api:
  mstoapi:
  secmsapp:
  fortress:
  client:

