apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  # These values should be base64 encoded
  # In production, use external secret management like Kubernetes secrets or sealed-secrets
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  database: {{ .Values.postgresql.auth.database | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
