version: '3.9'
services:
  account:
    image: ${AWS_SERVER_IMAGE}
    hostname: account
    # build: .
    entrypoint: [/home/moviefav/server/start, account]
    labels:
        - 'com.moviefav.description=account'
        - 'com.moviefav.server'
        - 'kompose.service.type=nodeport'
    restart: 'on-failure'
    env_file:
        - .env
    ports:
        - '4001:4001'
    # depends_on:
    #   - psqldb_secmsdb
    #   - redisdb_secmsdb
    networks:
        - secmsapp
        - secmsdbs
        - mstoapi

  movie:
    image: ${AWS_SERVER_IMAGE}
    hostname: movie
    # build: .
    entrypoint: [/home/moviefav/server/start, movie]
    labels:
      - "com.moviefav.description=movie"
      - "com.moviefav.server"
      - "kompose.service.type=nodeport"
    restart: "on-failure"
    env_file:
      - .env
    ports:
      - "4002:4002"
    # depends_on:
    #   - psqldb_secmsdb
    #   - redisdb_secmsdb
    networks:
      - secmsapp
      - secmsdbs
      - mstoapi

# LINE-REF-DONT-DELETE
# CONST-REF-DONT-DELETE
###################################################
# List of all networks needed
#
networks:
  secmsapp:
  secmsdbs:
  mstoapi: