#!/usr/bin/python
# Copyright © 2022 by Richard Maku
# All Rights Reserved. Proprietary and confidential.

import os,sys

os.chdir(os.path.abspath(os.path.dirname(__file__)))

args = len(sys.argv) - 1

if args > 0:
    service_name = sys.argv[1];
    target_dir = "apps/" + service_name + '/src/app_lib/'
    if not os.path.isdir(target_dir):
        print("No such service: " + service_name)
        exit(1)
    os.chdir(os.path.abspath(target_dir))

if args == 1:
    os.execlp('python', 'python', 'app.py')
else:
    print("Use: start [service name]")
    raise SystemExit(1)