version: '3.9'
services:
  redisdb_secmsdb:
    container_name: redisdb_secmsdb
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning --requirepass ${DB_REDIS_PASSWORD}
    volumes: 
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      # - cache:/data
      - "./tmp/data/redis_genmsdbtest/data:/usr/local/etc/redis/data:delegated"
    env_file:
      - .env
    networks:
      - secmsdbs
networks:
  secmsdbs:
volumes:
  redis_genmsdbtest:
  # cache:
  #   driver: local