name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test-microservices:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [account, links, monxt, movie, notifications, person, shows]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-
            ${{ runner.os }}-buildx-

      - name: Configure Docker cache
        run: |
          # Set up buildx cache configuration
          export DOCKER_BUILDKIT=1
          export BUILDX_CACHE_FROM="type=local,src=/tmp/.buildx-cache"
          export BUILDX_CACHE_TO="type=local,dest=/tmp/.buildx-cache-new,mode=max"

      - name: Run microservice tests
        env:
          CICD_MODE: "True"
          DOCKER_BUILDKIT: 1
          BUILDX_CACHE_FROM: "type=local,src=/tmp/.buildx-cache"
          BUILDX_CACHE_TO: "type=local,dest=/tmp/.buildx-cache-new,mode=max"
        run: |
          set -e  # Exit on any command failure
          chmod +x ./run.sh
          ./run.sh docker test up ${{ matrix.service }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache || true

      - name: Cleanup
        if: always()
        run: |
          ./run.sh docker test down
          docker system prune -f

  # security-scan:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: "fs"
  #         scan-ref: "."
  #         format: "sarif"
  #         output: "trivy-results.sarif"

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       if: always()
  #       with:
  #         sarif_file: "trivy-results.sarif"

  # dependency-review:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'

  #   steps:
  #     - name: Dependency Review
  #       uses: actions/dependency-review-action@v4
